# Generated by Django 3.1.7 on 2021-06-26 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
