# Generated by Django 3.1.7 on 2021-06-27 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0005_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='media/default.png', null=True, upload_to='media'),
        ),
    ]
