# Generated by Django 3.1.7 on 2021-06-27 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0007_auto_20210627_1523'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='media'),
        ),
    ]
