# Generated by Django 3.1.7 on 2021-06-27 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0009_auto_20210627_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='media/default.png', null=True, upload_to='media'),
        ),
    ]
