# Generated by Django 3.1.7 on 2021-06-27 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0010_auto_20210627_1648'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagepublic',
            name='file',
            field=models.FileField(null=True, upload_to='multimedia'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
