# Generated by Django 3.1.7 on 2021-06-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0012_auto_20210629_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room',
            field=models.CharField(max_length=1000, unique=True),
        ),
    ]
