# Generated by Django 3.1.7 on 2021-06-29 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0013_auto_20210629_2250'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagegroup',
            name='user',
            field=models.CharField(max_length=1000),
        ),
    ]
