# Generated by Django 3.1.7 on 2021-06-30 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0015_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='chatapp.room'),
        ),
    ]
