# Generated by Django 3.1.7 on 2021-06-30 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0016_notification_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='room',
            field=models.CharField(max_length=1000),
        ),
    ]
