# Generated by Django 3.1.7 on 2021-06-30 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0019_auto_20210630_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagegroup',
            name='content',
            field=models.CharField(max_length=10000000),
        ),
    ]
